name: universal_transformer
dependencies:
  - python=3.8.11
  - pip:
    - joblib==1.0.1
    - jupyter==1.0.0
    - numpy==1.21.1
    - pandas==1.3.1
    - pytest==6.2.4
    - spacy==3.1.1
    - torch==1.9.0
    - tqdm==4.62.0
    - tokenizers==0.10.3
    - transformers==4.9.1
    - datasets==1.11.0
    - wandb==0.11.2
