wandb_version: 1
tokenizer:
  value: 'hugging_face_word_level'
output_tokenizer:
  value: 'hugging_face_word_level'
vectors:
  value: 'random'
output_vectors:
  value: 'random'
vectors.vector_size:
  value: 90
dataset:
  value: 'wmt'
model:
  value: 'universal_transformer'
optimizer:
  value: 'adam'
epochs:
  value: 10
batch_size:
  value: 4
lr:
  value: 0.0001
log:
  value: null
learning_rate_decay_schedule:
  value: null
log_freq:
  value: null
dataset.debug:
  value: True
model.nhead:
  value: 3
model.max_steps:
  value: 6
